spring:
  datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url:  jdbc:mysql://127.0.0.1:3306/boya_demo?useUnicode=true&characterEncoding=UTF-
  8&useSSL=false&allowPublicKeyRetrieval=true
  username: root
  password: 123456
  redis:
  port: 6379
  # session:
  # store-type: none
 
  profiles:
    #    active: prod #发布版
    #active: dev  #开发版 远程库
    active: test  #测试版 本地库
  #  null 不返回
  jackson:
    default-property-inclusion: non_null